In [1]:
import numpy as np
import pandas as pd

In [2]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [4]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [6]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [7]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]= x*x

In [8]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [9]:
b= np.arange(3,15,4).reshape(3,1)

In [10]:
b

array([[ 3],
       [ 7],
       [11]])

In [11]:
ser= pd.Series(np.random.rand(10))

In [12]:
ser

0    0.998512
1    0.931365
2    0.448559
3    0.423123
4    0.521710
5    0.583140
6    0.577321
7    0.293942
8    0.810880
9    0.914653
dtype: float64

In [13]:
type(ser)

pandas.core.series.Series

In [14]:
newdf= pd.DataFrame(np.random.rand(20,5),index= np.arange(20))

In [15]:
type(newdf)

pandas.core.frame.DataFrame

In [16]:
newdf.describe()

0          1          2          3          4
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean    0.636643   0.454217   0.518132   0.434131   0.592759
std     0.287524   0.311236   0.273365   0.298196   0.303507
min     0.153754   0.023977   0.097361   0.010503   0.046215
25%     0.428034   0.176995   0.251261   0.175150   0.450097
50%     0.673135   0.445486   0.591724   0.434632   0.642225
75%     0.906853   0.747671   0.692057   0.666370   0.825386
max     0.992637   0.900432   0.927598   0.918161   0.990509

In [17]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [18]:
newdf[0][0]= 'harry'

In [19]:
newdf

0         1         2         3         4
0      harry  0.064419  0.587470  0.861060  0.988480
1   0.750014  0.394283  0.857570  0.918161  0.764260
2   0.915207  0.144999  0.546189  0.133309  0.480993
3    0.33199  0.023977  0.265402  0.037042  0.704847
4   0.986969  0.900432  0.208836  0.404552  0.434729
5   0.920505  0.624542  0.595978  0.906911  0.663204
6   0.222141  0.533731  0.835414  0.339504  0.162104
7   0.153754  0.737312  0.207029  0.394965  0.455219
8   0.194836  0.089101  0.627324  0.060864  0.863873
9    0.33513  0.866397  0.446016  0.725435  0.986158
10  0.720175  0.855493  0.097361  0.496902  0.818975
11  0.904068  0.486906  0.678806  0.464712  0.504581
12  0.494919  0.404066  0.121290  0.228192  0.176409
13  0.459001  0.073251  0.104277  0.701719  0.844617
14  0.479515  0.745555  0.731809  0.010503  0.046215
15   0.57226  0.201730  0.668287  0.654588  0.544167
16  0.975058  0.783949  0.348319  0.189097  0.754574
17  0.992637  0.212523  0.678265  0.476825  0.050017
18  0.883107  0.754019  0.927598  0.602609  0.621246
19  0.815487  0.187661  0.829401  0.075667  0.990509

In [20]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [21]:
newdf.index

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype='int32')

In [22]:
 newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [23]:
newdf.to_numpy()

array([['harry', 0.06441892690859952, 0.5874704940826906,
        0.8610604079913691, 0.9884796127367254],
       [0.75001369337639, 0.3942833481521243, 0.8575703166985673,
        0.9181614808506319, 0.7642603540372636],
       [0.9152073627893289, 0.14499918833336511, 0.5461893569696107,
        0.13330892476948508, 0.4809934255274696],
       [0.3319902035791815, 0.023976566937812804, 0.26540219743991755,
        0.03704184913628017, 0.7048474878638722],
       [0.9869694977319372, 0.9004320676211693, 0.20883641264313468,
        0.40455163598283017, 0.4347294081277092],
       [0.9205052723529968, 0.6245416798946204, 0.5959776508552471,
        0.906910725426068, 0.6632035618520135],
       [0.22214075690895785, 0.5337311564946707, 0.8354140637945737,
        0.33950420761643163, 0.1621044535807349],
       [0.1537536212835644, 0.7373115541913249, 0.20702935693060165,
        0.39496525922761305, 0.4552189269856375],
       [0.19483634496671132, 0.08910127544244761, 0.6273240544440

In [24]:
newdf[0][0]= 0.3241

In [25]:
newdf.to_numpy()

array([[0.3241, 0.06441892690859952, 0.5874704940826906,
        0.8610604079913691, 0.9884796127367254],
       [0.75001369337639, 0.3942833481521243, 0.8575703166985673,
        0.9181614808506319, 0.7642603540372636],
       [0.9152073627893289, 0.14499918833336511, 0.5461893569696107,
        0.13330892476948508, 0.4809934255274696],
       [0.3319902035791815, 0.023976566937812804, 0.26540219743991755,
        0.03704184913628017, 0.7048474878638722],
       [0.9869694977319372, 0.9004320676211693, 0.20883641264313468,
        0.40455163598283017, 0.4347294081277092],
       [0.9205052723529968, 0.6245416798946204, 0.5959776508552471,
        0.906910725426068, 0.6632035618520135],
       [0.22214075690895785, 0.5337311564946707, 0.8354140637945737,
        0.33950420761643163, 0.1621044535807349],
       [0.1537536212835644, 0.7373115541913249, 0.20702935693060165,
        0.39496525922761305, 0.4552189269856375],
       [0.19483634496671132, 0.08910127544244761, 0.62732405444401

In [26]:
newdf.T

0         1         2         3         4         5         6   \
0    0.3241  0.750014  0.915207   0.33199  0.986969  0.920505  0.222141   
1  0.064419  0.394283  0.144999  0.023977  0.900432  0.624542  0.533731   
2   0.58747   0.85757  0.546189  0.265402  0.208836  0.595978  0.835414   
3   0.86106  0.918161  0.133309  0.037042  0.404552  0.906911  0.339504   
4   0.98848   0.76426  0.480993  0.704847  0.434729  0.663204  0.162104   

         7         8         9         10        11        12        13  \
0  0.153754  0.194836   0.33513  0.720175  0.904068  0.494919  0.459001   
1  0.737312  0.089101  0.866397  0.855493  0.486906  0.404066  0.073251   
2  0.207029  0.627324  0.446016  0.097361  0.678806   0.12129  0.104277   
3  0.394965  0.060864  0.725435  0.496902  0.464712  0.228192  0.701719   
4  0.455219  0.863873  0.986158  0.818975  0.504581  0.176409  0.844617   

         14        15        16        17        18        19  
0  0.479515   0.57226  0.975058  0.992637  0.883107  0.815487  
1  0.745555   0.20173  0.783949  0.212523  0.754019  0.187661  
2  0.731809  0.668287  0.348319  0.678265  0.927598  0.829401  
3  0.010503  0.654588  0.189097  0.476825  0.602609  0.075667  
4  0.046215  0.544167  0.754574  0.050017  0.621246  0.990509

In [27]:
newdf.head()

0         1         2         3         4
0    0.3241  0.064419  0.587470  0.861060  0.988480
1  0.750014  0.394283  0.857570  0.918161  0.764260
2  0.915207  0.144999  0.546189  0.133309  0.480993
3   0.33199  0.023977  0.265402  0.037042  0.704847
4  0.986969  0.900432  0.208836  0.404552  0.434729

In [28]:
newdf.sort_index(axis=0, ascending=False)

0         1         2         3         4
19  0.815487  0.187661  0.829401  0.075667  0.990509
18  0.883107  0.754019  0.927598  0.602609  0.621246
17  0.992637  0.212523  0.678265  0.476825  0.050017
16  0.975058  0.783949  0.348319  0.189097  0.754574
15   0.57226  0.201730  0.668287  0.654588  0.544167
14  0.479515  0.745555  0.731809  0.010503  0.046215
13  0.459001  0.073251  0.104277  0.701719  0.844617
12  0.494919  0.404066  0.121290  0.228192  0.176409
11  0.904068  0.486906  0.678806  0.464712  0.504581
10  0.720175  0.855493  0.097361  0.496902  0.818975
9    0.33513  0.866397  0.446016  0.725435  0.986158
8   0.194836  0.089101  0.627324  0.060864  0.863873
7   0.153754  0.737312  0.207029  0.394965  0.455219
6   0.222141  0.533731  0.835414  0.339504  0.162104
5   0.920505  0.624542  0.595978  0.906911  0.663204
4   0.986969  0.900432  0.208836  0.404552  0.434729
3    0.33199  0.023977  0.265402  0.037042  0.704847
2   0.915207  0.144999  0.546189  0.133309  0.480993
1   0.750014  0.394283  0.857570  0.918161  0.764260
0     0.3241  0.064419  0.587470  0.861060  0.988480

In [29]:
newdf.loc[0,0]= 654

In [30]:
newdf

0         1         2         3         4
0        654  0.064419  0.587470  0.861060  0.988480
1   0.750014  0.394283  0.857570  0.918161  0.764260
2   0.915207  0.144999  0.546189  0.133309  0.480993
3    0.33199  0.023977  0.265402  0.037042  0.704847
4   0.986969  0.900432  0.208836  0.404552  0.434729
5   0.920505  0.624542  0.595978  0.906911  0.663204
6   0.222141  0.533731  0.835414  0.339504  0.162104
7   0.153754  0.737312  0.207029  0.394965  0.455219
8   0.194836  0.089101  0.627324  0.060864  0.863873
9    0.33513  0.866397  0.446016  0.725435  0.986158
10  0.720175  0.855493  0.097361  0.496902  0.818975
11  0.904068  0.486906  0.678806  0.464712  0.504581
12  0.494919  0.404066  0.121290  0.228192  0.176409
13  0.459001  0.073251  0.104277  0.701719  0.844617
14  0.479515  0.745555  0.731809  0.010503  0.046215
15   0.57226  0.201730  0.668287  0.654588  0.544167
16  0.975058  0.783949  0.348319  0.189097  0.754574
17  0.992637  0.212523  0.678265  0.476825  0.050017
18  0.883107  0.754019  0.927598  0.602609  0.621246
19  0.815487  0.187661  0.829401  0.075667  0.990509

In [31]:
newdf.columns= list("ABCDE")

In [32]:
newdf

A         B         C         D         E
0        654  0.064419  0.587470  0.861060  0.988480
1   0.750014  0.394283  0.857570  0.918161  0.764260
2   0.915207  0.144999  0.546189  0.133309  0.480993
3    0.33199  0.023977  0.265402  0.037042  0.704847
4   0.986969  0.900432  0.208836  0.404552  0.434729
5   0.920505  0.624542  0.595978  0.906911  0.663204
6   0.222141  0.533731  0.835414  0.339504  0.162104
7   0.153754  0.737312  0.207029  0.394965  0.455219
8   0.194836  0.089101  0.627324  0.060864  0.863873
9    0.33513  0.866397  0.446016  0.725435  0.986158
10  0.720175  0.855493  0.097361  0.496902  0.818975
11  0.904068  0.486906  0.678806  0.464712  0.504581
12  0.494919  0.404066  0.121290  0.228192  0.176409
13  0.459001  0.073251  0.104277  0.701719  0.844617
14  0.479515  0.745555  0.731809  0.010503  0.046215
15   0.57226  0.201730  0.668287  0.654588  0.544167
16  0.975058  0.783949  0.348319  0.189097  0.754574
17  0.992637  0.212523  0.678265  0.476825  0.050017
18  0.883107  0.754019  0.927598  0.602609  0.621246
19  0.815487  0.187661  0.829401  0.075667  0.990509

In [33]:
newdf.head(2)

A         B        C         D        E
0       654  0.064419  0.58747  0.861060  0.98848
1  0.750014  0.394283  0.85757  0.918161  0.76426

In [34]:
newdf.loc[0,'A']= 6543

In [41]:
newdf

A         B         C         D         E
0       6543  0.064419  0.587470  0.861060  0.988480
1   0.750014  0.394283  0.857570  0.918161  0.764260
2   0.915207  0.144999  0.546189  0.133309  0.480993
3    0.33199  0.023977  0.265402  0.037042  0.704847
4   0.986969  0.900432  0.208836  0.404552  0.434729
5   0.920505  0.624542  0.595978  0.906911  0.663204
6   0.222141  0.533731  0.835414  0.339504  0.162104
7   0.153754  0.737312  0.207029  0.394965  0.455219
8   0.194836  0.089101  0.627324  0.060864  0.863873
9    0.33513  0.866397  0.446016  0.725435  0.986158
10  0.720175  0.855493  0.097361  0.496902  0.818975
11  0.904068  0.486906  0.678806  0.464712  0.504581
12  0.494919  0.404066  0.121290  0.228192  0.176409
13  0.459001  0.073251  0.104277  0.701719  0.844617
14  0.479515  0.745555  0.731809  0.010503  0.046215
15   0.57226  0.201730  0.668287  0.654588  0.544167
16  0.975058  0.783949  0.348319  0.189097  0.754574
17  0.992637  0.212523  0.678265  0.476825  0.050017
18  0.883107  0.754019  0.927598  0.602609  0.621246
19  0.815487  0.187661  0.829401  0.075667  0.990509

In [42]:
newdf.drop(0,axis=0)

A         B         C         D         E
1   0.750014  0.394283  0.857570  0.918161  0.764260
2   0.915207  0.144999  0.546189  0.133309  0.480993
3    0.33199  0.023977  0.265402  0.037042  0.704847
4   0.986969  0.900432  0.208836  0.404552  0.434729
5   0.920505  0.624542  0.595978  0.906911  0.663204
6   0.222141  0.533731  0.835414  0.339504  0.162104
7   0.153754  0.737312  0.207029  0.394965  0.455219
8   0.194836  0.089101  0.627324  0.060864  0.863873
9    0.33513  0.866397  0.446016  0.725435  0.986158
10  0.720175  0.855493  0.097361  0.496902  0.818975
11  0.904068  0.486906  0.678806  0.464712  0.504581
12  0.494919  0.404066  0.121290  0.228192  0.176409
13  0.459001  0.073251  0.104277  0.701719  0.844617
14  0.479515  0.745555  0.731809  0.010503  0.046215
15   0.57226  0.201730  0.668287  0.654588  0.544167
16  0.975058  0.783949  0.348319  0.189097  0.754574
17  0.992637  0.212523  0.678265  0.476825  0.050017
18  0.883107  0.754019  0.927598  0.602609  0.621246
19  0.815487  0.187661  0.829401  0.075667  0.990509

In [45]:
newdf.loc[[1,2],:]

A         B         C         D         E
1  0.750014  0.394283  0.857570  0.918161  0.764260
2  0.915207  0.144999  0.546189  0.133309  0.480993

In [48]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.1)]

A         B         C         D         E
6  0.222141  0.533731  0.835414  0.339504  0.162104
7  0.153754  0.737312  0.207029  0.394965  0.455219
8  0.194836  0.089101  0.627324  0.060864  0.863873

In [51]:
newdf.iloc[[0,5],[1,2]]

B         C
0  0.064419  0.587470
5  0.624542  0.595978

In [52]:
newdf.drop(['A','D'],axis=1, inplace= True)

In [53]:
newdf

B         C         E
0   0.064419  0.587470  0.988480
1   0.394283  0.857570  0.764260
2   0.144999  0.546189  0.480993
3   0.023977  0.265402  0.704847
4   0.900432  0.208836  0.434729
5   0.624542  0.595978  0.663204
6   0.533731  0.835414  0.162104
7   0.737312  0.207029  0.455219
8   0.089101  0.627324  0.863873
9   0.866397  0.446016  0.986158
10  0.855493  0.097361  0.818975
11  0.486906  0.678806  0.504581
12  0.404066  0.121290  0.176409
13  0.073251  0.104277  0.844617
14  0.745555  0.731809  0.046215
15  0.201730  0.668287  0.544167
16  0.783949  0.348319  0.754574
17  0.212523  0.678265  0.050017
18  0.754019  0.927598  0.621246
19  0.187661  0.829401  0.990509

In [54]:
newdf.drop([1,5], axis=0, inplace= True)

In [55]:
newdf

B         C         E
0   0.064419  0.587470  0.988480
2   0.144999  0.546189  0.480993
3   0.023977  0.265402  0.704847
4   0.900432  0.208836  0.434729
6   0.533731  0.835414  0.162104
7   0.737312  0.207029  0.455219
8   0.089101  0.627324  0.863873
9   0.866397  0.446016  0.986158
10  0.855493  0.097361  0.818975
11  0.486906  0.678806  0.504581
12  0.404066  0.121290  0.176409
13  0.073251  0.104277  0.844617
14  0.745555  0.731809  0.046215
15  0.201730  0.668287  0.544167
16  0.783949  0.348319  0.754574
17  0.212523  0.678265  0.050017
18  0.754019  0.927598  0.621246
19  0.187661  0.829401  0.990509

In [57]:
 newdf.reset_index(drop= True)

B         C         E
0   0.064419  0.587470  0.988480
1   0.144999  0.546189  0.480993
2   0.023977  0.265402  0.704847
3   0.900432  0.208836  0.434729
4   0.533731  0.835414  0.162104
5   0.737312  0.207029  0.455219
6   0.089101  0.627324  0.863873
7   0.866397  0.446016  0.986158
8   0.855493  0.097361  0.818975
9   0.486906  0.678806  0.504581
10  0.404066  0.121290  0.176409
11  0.073251  0.104277  0.844617
12  0.745555  0.731809  0.046215
13  0.201730  0.668287  0.544167
14  0.783949  0.348319  0.754574
15  0.212523  0.678265  0.050017
16  0.754019  0.927598  0.621246
17  0.187661  0.829401  0.990509

In [61]:
newdf.loc[:,['B']]=None

In [62]:
newdf

B         C         E
0   None  0.587470  0.988480
2   None  0.546189  0.480993
3   None  0.265402  0.704847
4   None  0.208836  0.434729
6   None  0.835414  0.162104
7   None  0.207029  0.455219
8   None  0.627324  0.863873
9   None  0.446016  0.986158
10  None  0.097361  0.818975
11  None  0.678806  0.504581
12  None  0.121290  0.176409
13  None  0.104277  0.844617
14  None  0.731809  0.046215
15  None  0.668287  0.544167
16  None  0.348319  0.754574
17  None  0.678265  0.050017
18  None  0.927598  0.621246
19  None  0.829401  0.990509